
[window]
padding = { x=0, y=0 }
dynamic_padding = true
decorations = "None"
opacity = 1
blur = false

[font]
normal = {family = "ZedMono Nerd Font"}
size = 16
offset = {
    x = 0,
    y = 0,
}

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "None" },
]

[colors]
cursor = {
    # text = "#FFFFFF",
    # cursor = "#FFFFFF",
}

[cursor]
vi_mode_style = {
    shape = "Block",
    blinking = "off",
}
