
[font]
normal = ["ZedMono Nerd Font Mono"]
size = 13

[font.features]
"ZedMono Nerd Font Mono" = ["-calt"]

[window]
padding_top = 0
padding_left = 0
padding_right = 0
padding_bottom = 0

fork = true
